name: Update Publications

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  generate-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r utils/requirements.txt

      - name: Get New Publications
        run: |
          source venv/bin/activate
          python3 utils/scholar_scraper.py

      - name: Update publications.html
        run: |
          source venv/bin/activate
          python3 utils/copy_scraped_publications.py

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add publications.html
          git add utils/scraped_publications.html
          git commit -m "Update HTML content" || echo "Nothing to push"
          git push
